// AUTO-GENERATED by scripts/gen-sw.mjs — DO NOT EDIT BY HAND
// 캐시 전략: 로컬 자산 = cache-first, 폰트 = stale-while-revalidate.
const CACHE_VERSION = 'morpheme-detective-v8';

const APP_SHELL_URLS = [
  '/',
  'index.html',
  'manifest.webmanifest',
  'src/css/tokens.css',
  'src/css/base.css',
  'src/css/components.css',
  'src/css/screens.css',
  'src/css/stage.css',
  'src/css/magnifier.css',
  'src/css/word-blocks.css',
  'src/css/morph.css',
  'src/css/card-deck.css',
  'src/js/config.js',
  'src/js/state.js',
  'src/js/utils.js',
  'src/js/hangul.js',
  'src/js/tts.js',
  'src/js/audio.js',
  'src/js/storage.js',
  'src/js/settings.js',
  'src/js/pointer.js',
  'src/js/viewport.js',
  'src/js/magnifier.js',
  'src/js/word-block.js',
  'src/js/morph.js',
  'src/js/card-deck.js',
  'src/js/stage.js',
  'src/js/game.js',
  'src/js/progress.js',
  'src/js/mission.js',
  'src/js/collection.js',
  'src/js/main.js',
  'src/data/hanja.js',
  'src/data/vocab.js',
  'src/data/stages.js',
  'src/assets/stages/parking-lot.svg',
  'src/assets/stages/classroom.svg',
  'src/assets/stages/family-home.svg',
  'src/assets/stages/school-cafeteria.svg',
  'src/assets/stages/fire-station.svg',
  'src/assets/stages/nature-park.svg',
  'src/assets/stages/market.svg',
  'src/assets/stages/sky-time.svg',
  'src/assets/stages/street.svg',
  'src/assets/stages/numbers-class.svg',
  'src/assets/hanja/車.json',
  'src/assets/hanja/場.json',
  'src/assets/hanja/道.json',
  'src/assets/hanja/動.json',
  'src/assets/hanja/力.json',
  'src/assets/hanja/立.json',
  'src/assets/hanja/方.json',
  'src/assets/hanja/自.json',
  'src/assets/hanja/全.json',
  'src/assets/hanja/工.json',
  'src/assets/hanja/教.json',
  'src/assets/hanja/校.json',
  'src/assets/hanja/學.json',
  'src/assets/hanja/生.json',
  'src/assets/hanja/室.json',
  'src/assets/hanja/先.json',
  'src/assets/hanja/兄.json',
  'src/assets/hanja/弟.json',
  'src/assets/hanja/國.json',
  'src/assets/hanja/韓.json',
  'src/assets/hanja/家.json',
  'src/assets/hanja/父.json',
  'src/assets/hanja/母.json',
  'src/assets/hanja/男.json',
  'src/assets/hanja/女.json',
  'src/assets/hanja/子.json',
  'src/assets/hanja/寸.json',
  'src/assets/hanja/姓.json',
  'src/assets/hanja/名.json',
  'src/assets/hanja/孝.json',
  'src/assets/hanja/食.json',
  'src/assets/hanja/木.json',
  'src/assets/hanja/人.json',
  'src/assets/hanja/水.json',
  'src/assets/hanja/手.json',
  'src/assets/hanja/安.json',
  'src/assets/hanja/答.json',
  'src/assets/hanja/事.json',
  'src/assets/hanja/右.json',
  'src/assets/hanja/左.json',
  'src/assets/hanja/火.json',
  'src/assets/hanja/軍.json',
  'src/assets/hanja/民.json',
  'src/assets/hanja/直.json',
  'src/assets/hanja/正.json',
  'src/assets/hanja/不.json',
  'src/assets/hanja/平.json',
  'src/assets/hanja/上.json',
  'src/assets/hanja/下.json',
  'src/assets/hanja/後.json',
  'src/assets/hanja/山.json',
  'src/assets/hanja/江.json',
  'src/assets/hanja/海.json',
  'src/assets/hanja/漢.json',
  'src/assets/hanja/萬.json',
  'src/assets/hanja/中.json',
  'src/assets/hanja/小.json',
  'src/assets/hanja/大.json',
  'src/assets/hanja/土.json',
  'src/assets/hanja/農.json',
  'src/assets/hanja/市.json',
  'src/assets/hanja/物.json',
  'src/assets/hanja/金.json',
  'src/assets/hanja/每.json',
  'src/assets/hanja/世.json',
  'src/assets/hanja/間.json',
  'src/assets/hanja/時.json',
  'src/assets/hanja/午.json',
  'src/assets/hanja/前.json',
  'src/assets/hanja/內.json',
  'src/assets/hanja/日.json',
  'src/assets/hanja/月.json',
  'src/assets/hanja/年.json',
  'src/assets/hanja/氣.json',
  'src/assets/hanja/空.json',
  'src/assets/hanja/長.json',
  'src/assets/hanja/靑.json',
  'src/assets/hanja/白.json',
  'src/assets/hanja/西.json',
  'src/assets/hanja/東.json',
  'src/assets/hanja/門.json',
  'src/assets/hanja/外.json',
  'src/assets/hanja/電.json',
  'src/assets/hanja/話.json',
  'src/assets/hanja/記.json',
  'src/assets/hanja/活.json',
  'src/assets/hanja/王.json',
  'src/assets/hanja/北.json',
  'src/assets/hanja/南.json',
  'src/assets/hanja/足.json',
  'src/assets/hanja/一.json',
  'src/assets/hanja/二.json',
  'src/assets/hanja/三.json',
  'src/assets/hanja/四.json',
  'src/assets/hanja/五.json',
  'src/assets/hanja/六.json',
  'src/assets/hanja/七.json',
  'src/assets/hanja/八.json',
  'src/assets/hanja/九.json',
  'src/assets/hanja/十.json',
];

async function cacheFirst(request, cacheName) {
  const cache = await caches.open(cacheName);
  const cached = await cache.match(request);
  if (cached) return cached;

  try {
    const response = await fetch(request);
    if (response.ok) {
      cache.put(request, response.clone());
    }
    return response;
  } catch (err) {
    return new Response('Offline - resource not cached', { status: 503 });
  }
}

async function staleWhileRevalidate(request, cacheName) {
  const cache = await caches.open(cacheName);
  const cached = await cache.match(request);

  const fetchPromise = fetch(request).then(response => {
    if (response.ok) {
      cache.put(request, response.clone());
    }
    return response;
  }).catch(() => cached || new Response('Offline', { status: 503 }));

  return cached || fetchPromise;
}

async function networkFirst(request, cacheName) {
  const cache = await caches.open(cacheName);

  try {
    const response = await fetch(request);
    if (response.ok) {
      cache.put(request, response.clone());
    }
    return response;
  } catch (err) {
    const cached = await cache.match(request);
    return cached || new Response('Offline', { status: 503 });
  }
}

self.addEventListener('install', e => {
  e.waitUntil(
    caches.open(CACHE_VERSION).then(cache => {
      return cache.addAll(APP_SHELL_URLS);
    }).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys().then(names => {
      return Promise.all(
        names
          .filter(name => name !== CACHE_VERSION)
          .map(name => caches.delete(name))
      );
    }).then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', e => {
  const url = new URL(e.request.url);
  const isLocal = url.origin === self.location.origin;
  const isFont = url.hostname.includes('googleapis.com') || url.hostname.includes('gstatic.com');
  const isAppShell = isLocal && (
    url.pathname === '/' ||
    url.pathname.endsWith('.html') ||
    url.pathname.includes('/src/css/') ||
    url.pathname.includes('/src/js/') ||
    url.pathname.includes('/src/data/') ||
    url.pathname.includes('/src/assets/') ||
    url.pathname.endsWith('manifest.webmanifest')
  );

  if (isAppShell) {
    e.respondWith(cacheFirst(e.request, CACHE_VERSION));
  } else if (isFont) {
    e.respondWith(staleWhileRevalidate(e.request, CACHE_VERSION));
  } else {
    e.respondWith(networkFirst(e.request, CACHE_VERSION));
  }
});
