#!/usr/bin/env node
// hanja.js (HANJA_IDS) + stages.js (STAGE_IDS) 기반으로 service-worker.js 의
// APP_SHELL_URLS 를 동적으로 만들어 SW 전체를 재 emit.
//
// CACHE_VERSION 이 자동으로 bump 된다 — 매 호출마다 + 1.
//
// 사용: node scripts/gen-sw.mjs

import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);
const ROOT       = path.resolve(__dirname, '..');
const OUT_PATH   = path.join(ROOT, 'service-worker.js');

const STATIC_ASSETS = [
  '/',
  'index.html',
  'manifest.webmanifest',
  'src/css/tokens.css',
  'src/css/base.css',
  'src/css/components.css',
  'src/css/screens.css',
  'src/css/stage.css',
  'src/css/magnifier.css',
  'src/css/word-blocks.css',
  'src/css/morph.css',
  'src/css/card-deck.css',
  'src/js/config.js',
  'src/js/state.js',
  'src/js/utils.js',
  'src/js/hangul.js',
  'src/js/tts.js',
  'src/js/audio.js',
  'src/js/storage.js',
  'src/js/settings.js',
  'src/js/pointer.js',
  'src/js/viewport.js',
  'src/js/magnifier.js',
  'src/js/word-block.js',
  'src/js/morph.js',
  'src/js/card-deck.js',
  'src/js/stage.js',
  'src/js/game.js',
  'src/js/progress.js',
  'src/js/mission.js',
  'src/js/collection.js',
  'src/js/main.js',
  'src/data/hanja.js',
  'src/data/vocab.js',
  'src/data/stages.js',
];

async function detectCurrentVersion() {
  try {
    const txt = await fs.readFile(OUT_PATH, 'utf8');
    const m = txt.match(/CACHE_VERSION\s*=\s*'morpheme-detective-v(\d+)'/);
    return m ? Number(m[1]) : 3;
  } catch { return 3; }
}

function makeSw(version, urls) {
  const urlsBlock = urls.map(u => `  '${u}',`).join('\n');
  return `// AUTO-GENERATED by scripts/gen-sw.mjs — DO NOT EDIT BY HAND
// 캐시 전략: 로컬 자산 = cache-first, 폰트 = stale-while-revalidate.
const CACHE_VERSION = 'morpheme-detective-v${version}';

const APP_SHELL_URLS = [
${urlsBlock}
];

async function cacheFirst(request, cacheName) {
  const cache = await caches.open(cacheName);
  const cached = await cache.match(request);
  if (cached) return cached;

  try {
    const response = await fetch(request);
    if (response.ok) {
      cache.put(request, response.clone());
    }
    return response;
  } catch (err) {
    return new Response('Offline - resource not cached', { status: 503 });
  }
}

async function staleWhileRevalidate(request, cacheName) {
  const cache = await caches.open(cacheName);
  const cached = await cache.match(request);

  const fetchPromise = fetch(request).then(response => {
    if (response.ok) {
      cache.put(request, response.clone());
    }
    return response;
  }).catch(() => cached || new Response('Offline', { status: 503 }));

  return cached || fetchPromise;
}

async function networkFirst(request, cacheName) {
  const cache = await caches.open(cacheName);

  try {
    const response = await fetch(request);
    if (response.ok) {
      cache.put(request, response.clone());
    }
    return response;
  } catch (err) {
    const cached = await cache.match(request);
    return cached || new Response('Offline', { status: 503 });
  }
}

self.addEventListener('install', e => {
  e.waitUntil(
    caches.open(CACHE_VERSION).then(cache => {
      return cache.addAll(APP_SHELL_URLS);
    }).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys().then(names => {
      return Promise.all(
        names
          .filter(name => name !== CACHE_VERSION)
          .map(name => caches.delete(name))
      );
    }).then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', e => {
  const url = new URL(e.request.url);
  const isLocal = url.origin === self.location.origin;
  const isFont = url.hostname.includes('googleapis.com') || url.hostname.includes('gstatic.com');
  const isAppShell = isLocal && (
    url.pathname === '/' ||
    url.pathname.endsWith('.html') ||
    url.pathname.includes('/src/css/') ||
    url.pathname.includes('/src/js/') ||
    url.pathname.includes('/src/data/') ||
    url.pathname.includes('/src/assets/') ||
    url.pathname.endsWith('manifest.webmanifest')
  );

  if (isAppShell) {
    e.respondWith(cacheFirst(e.request, CACHE_VERSION));
  } else if (isFont) {
    e.respondWith(staleWhileRevalidate(e.request, CACHE_VERSION));
  } else {
    e.respondWith(networkFirst(e.request, CACHE_VERSION));
  }
});
`;
}

async function main() {
  const hanjaUrl  = pathToFileURL(path.join(ROOT, 'src', 'data', 'hanja.js'));
  const stagesUrl = pathToFileURL(path.join(ROOT, 'src', 'data', 'stages.js'));
  const { HANJA_IDS } = await import(hanjaUrl);
  const { STAGE_IDS } = await import(stagesUrl);

  const urls = [
    ...STATIC_ASSETS,
    ...STAGE_IDS.map(id => `src/assets/stages/${id}.svg`),
    ...HANJA_IDS.map(id => `src/assets/hanja/${id}.json`),
  ];

  const prev    = await detectCurrentVersion();
  const version = prev + 1;
  await fs.writeFile(OUT_PATH, makeSw(version, urls), 'utf8');
  console.log(`[gen-sw] v${prev} → v${version}, urls=${urls.length}`);
}

main().catch(e => { console.error(e); process.exit(1); });
