#!/usr/bin/env node
// hanja.js (HANJA.vocab) + stages.js (STAGES.words[].text) 에서 단어를 모으고,
// 음절-한자 매핑(syllableMap)을 자동 계산해서 src/data/vocab.js 를 emit.
//
// READING_VARIANTS: 두음법칙 · 한자음 변음 보정.
//
// familiarity: hanja.vocab 배열 위치(앞쪽 = 친숙) 기준. 여러 한자가 같은 단어를
// 공유하면 최소값 사용.
//
// 사용: node scripts/gen-vocab.mjs

import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);
const ROOT       = path.resolve(__dirname, '..');
const OUT_PATH   = path.join(ROOT, 'src', 'data', 'vocab.js');

// 한자 reading variants (두음법칙·변음)
const READING_VARIANTS = {
  '女': ['녀', '여'],
  '年': ['년', '연'],
  '力': ['력', '역'],
  '立': ['립', '입'],
  '六': ['육', '유'],
  '十': ['십', '시'],
  '不': ['불', '부'],
};

function getReadings(id, hanja) {
  return READING_VARIANTS[id] ?? [hanja.reading];
}

function ensureEntry(map, word) {
  if (!map[word]) {
    map[word] = { hanja: new Set(), syllableMap: {}, familiarity: 9 };
  }
  return map[word];
}

async function main() {
  const hanjaUrl  = pathToFileURL(path.join(ROOT, 'src', 'data', 'hanja.js'));
  const stagesUrl = pathToFileURL(path.join(ROOT, 'src', 'data', 'stages.js'));
  const { HANJA, HANJA_IDS } = await import(hanjaUrl);
  const { STAGES }           = await import(stagesUrl);

  const map = Object.create(null);

  // 1. hanja.vocab 등록 — 단어, familiarity, 그 한자 첫 매핑
  for (const id of HANJA_IDS) {
    const h = HANJA[id];
    h.vocab.forEach((word, i) => {
      const entry = ensureEntry(map, word);
      entry.hanja.add(id);
      entry.familiarity = Math.min(entry.familiarity, i + 1);
    });
  }

  // 2. stages.words 등록 — 명시적 targetSyllableIdx + targetHanjaId
  for (const stage of Object.values(STAGES)) {
    for (const w of Object.values(stage.words ?? {})) {
      const entry = ensureEntry(map, w.text);
      entry.hanja.add(w.targetHanjaId);
      entry.syllableMap[w.targetSyllableIdx] = w.targetHanjaId;
      if (entry.familiarity === 9) entry.familiarity = 2;
    }
  }

  // 3a. cross-check (entry.hanja 한정) — 정확도 우선
  // 단어가 명시적으로 가진 한자만 매핑 시도. 학교(校)에 教가 잘못 매핑되는 등을 막음.
  for (const word of Object.keys(map)) {
    const entry = map[word];
    const syllables = [...word];
    for (const id of entry.hanja) {
      const readings = getReadings(id, HANJA[id]);
      syllables.forEach((s, idx) => {
        if (readings.includes(s) && !entry.syllableMap[idx]) {
          entry.syllableMap[idx] = id;
        }
      });
    }
  }

  // 3b. gap-fill cross-check — 비어있는 idx 에 한해 100자 전체 시도
  // 예: 익명(姓.vocab) 의 명(名), 국립(立.vocab) 의 국(國) 등.
  for (const word of Object.keys(map)) {
    const entry = map[word];
    const syllables = [...word];
    for (const id of HANJA_IDS) {
      if (entry.hanja.has(id)) continue;
      const readings = getReadings(id, HANJA[id]);
      syllables.forEach((s, idx) => {
        if (readings.includes(s) && !entry.syllableMap[idx]) {
          entry.syllableMap[idx] = id;
          entry.hanja.add(id);
        }
      });
    }
  }

  // 3. emit
  const sortedWords = Object.keys(map).sort();
  const lines = [];
  lines.push('// AUTO-GENERATED by scripts/gen-vocab.mjs — DO NOT EDIT BY HAND');
  lines.push('// 어휘 → 한자 매핑. hanja.js + stages.js 로부터 자동 생성.');
  lines.push('// syllableMap: { 음절인덱스(0-based): HanjaId }');
  lines.push('// familiarity: 1=초1 빈출, 2=중간, 3+=드문 노출 → card-deck 정렬 키');
  lines.push('');
  lines.push('export const VOCAB = {');
  for (const w of sortedWords) {
    const e = map[w];
    const hanja = [...e.hanja].sort();
    const syMap = JSON.stringify(e.syllableMap);
    lines.push(`  '${w}': { hanja: ${JSON.stringify(hanja)}, syllableMap: ${syMap}, familiarity: ${e.familiarity} },`);
  }
  lines.push('};');
  lines.push('');

  await fs.writeFile(OUT_PATH, lines.join('\n'), 'utf8');
  console.log(`[gen-vocab] ${sortedWords.length} entries → ${path.relative(ROOT, OUT_PATH)}`);

  // 4. 검증 — 매핑이 비어있는 단어 경고
  let warned = 0;
  for (const w of sortedWords) {
    const e = map[w];
    if (Object.keys(e.syllableMap).length === 0) {
      console.warn(`[gen-vocab] WARN ${w}: empty syllableMap`);
      warned++;
    }
  }
  if (warned) console.warn(`[gen-vocab] ${warned} word(s) without syllableMap — check READING_VARIANTS`);
}

main().catch(e => { console.error(e); process.exit(1); });
